__title__ = 'Mayan EDMS'
__version__ = '4.9.8'
__build__ = 0x040908
__build_string__ = 'v4.9.8-128-g24aa055c8e8_Tue Apr 21 14:30:58 2026 -0400'
__django_version__ = '4.2'
__author__ = 'Roberto Rosario'
__author_email__ = 'roberto.rosario@mayan-edms.com'
__description__ = 'Free Open Source Electronic Document Management System'
__license__ = 'GPL 2.0'
__copyright_short__ = '2026 Roberto Rosario'
__copyright__ = '{} {}'.format('Copyright', __copyright_short__)
__website__ = 'https://www.mayan-edms.com'
