__title__ = 'Mayan EDMS'
__version__ = '4.11.3'
__build__ = 0x041103
__build_string__ = 'v4.11.2-161-g37cbd32ef05_Mon Apr 27 20:13:52 2026 -0400'
__django_version__ = '5.2'
__author__ = 'Roberto Rosario'
__author_email__ = 'roberto.rosario@mayan-edms.com'
__description__ = 'Free Open Source Electronic Document Management System'
__license__ = 'GPL 2.0'
__copyright_short__ = '2026 Roberto Rosario'
__copyright__ = '{} {}'.format('Copyright', __copyright_short__)
__website__ = 'https://www.mayan-edms.com'
